//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://eaidev.mobinil.com:5555/ws/MEAI_OnlineServices_2017.webServices.GO.checkDa" +
            "taProfileStatus_V2_WSDL/MEAI_OnlineServices_2017_webServices_GO_checkDataProfile" +
            "Status_V2_WSDL_Port")]
        public string BusinessLogicLayer_checkDataProfileStatus_MEAI_OnlineServices_2017_webServices_GO_checkDataProfileStatus_V2_WSDL {
            get {
                return ((string)(this["BusinessLogicLayer_checkDataProfileStatus_MEAI_OnlineServices_2017_webServices_GO" +
                    "_checkDataProfileStatus_V2_WSDL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://eaidev.mobinil.com:5555/ws/MEAI_OnlineServices_2015.webServices.SelfServic" +
            "es:getEligibleServiceClassesMigration_WSDL/MEAI_OnlineServices_2015_webServices_" +
            "SelfServices_getEligibleServiceClassesMigration_WSDL_Port")]
        public string BusinessLogicLayer_getEligibleServiceClassesMigration_getEligibleServiceClassesMigration_WSDL {
            get {
                return ((string)(this["BusinessLogicLayer_getEligibleServiceClassesMigration_getEligibleServiceClassesMi" +
                    "gration_WSDL"]));
            }
        }
    }
}
